'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 
 and 
, the first 
 terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

n = 4000000

def solve(n):
    a, b = 1,2

    ans = 0
    while b<=n:
        if b%2 == 0:
            ans +=b 
        a,b = b,a+b 
    return ans
print(solve(n))